version: '3'
services:
  broker-reverseproxy:
    image: registry.gitlab.cc-asp.fraunhofer.de/eis-ids/metadata-registry/reverseproxy:1.0.2
    volumes:
     - ./cert:/etc/cert/
    # - c:/etc/idscert/localhost:/etc/cert/
    ports:
    - "443:443" # IDS-HTTP API
    - "80:80"

  broker-core:
    image: registry.gitlab.cc-asp.fraunhofer.de/eis-ids/metadata-registry/core:1.0.2
    volumes:
      - ./cert:/etc/cert/
      #- c:/etc/idscert/localhost:/etc/cert/
    restart: always
    environment:
    - SPARQL_ENDPOINT=http://broker-fuseki:3030/connectorData
    - ELASTICSEARCH_HOSTNAME=broker-elasticsearch
    - SHACL_VALIDATION=true
    - DAPS_VALIDATE_INCOMING=true
    - IDENTITY_JAVAKEYSTORE=/etc/cert/isstbroker-keystore.jks
    - COMPONENT_URI=https://localhost/
    - COMPONENT_CATALOGURI=https://localhost/connectors/
    - JWKS_TRUSTEDHOSTS=daps.aisec.fraunhofer.de,omejdn
    expose:
    - "8080"

  broker-fuseki:
    image: registry.gitlab.cc-asp.fraunhofer.de/eis-ids/metadata-registry/fuseki:1.0.2
    volumes:
      - broker-fuseki:/fuseki
    expose:
    - "3030"

volumes:
    broker-fuseki:
