version: '3'
services:
  broker-reverseproxy:
    image: registry.gitlab.cc-asp.fraunhofer.de/tmorbagalh/apphandler/broker-open/reverseproxy:4.1.4
    volumes:
#      - /etc/idscert/localhost:/etc/cert/
       - c:/etc/idscert/localhost:/etc/cert/
    ports:
    - "443:443" # IDS-HTTP API
    - "80:80"

  broker-core:
    image: registry.gitlab.cc-asp.fraunhofer.de/tmorbagalh/apphandler/broker-open/core:v1
    volumes:
#     - /etc/idscert/localhost:/etc/cert/
       - c:/etc/idscert/localhost:/etc/cert/
    restart: always
    environment:
    - SPARQL_ENDPOINT=http://broker-fuseki:3030/connectorData
    - ELASTICSEARCH_HOSTNAME=broker-elasticsearch
    - SHACL_VALIDATION=true
    - DAPS_VALIDATE_INCOMING=true
    - COMPONENT_URI=https://localhost/
    - COMPONENT_CATALOGURI=https://localhost/connectors/
    expose:
    - "8080"

  broker-fuseki:
    image: registry.gitlab.cc-asp.fraunhofer.de/tmorbagalh/apphandler/broker-open/fuseki:4.1.4
    volumes:
      - broker-fuseki:/fuseki
    expose:
    - "3030"

volumes:
    broker-fuseki:

